### ISSUE TITLE
Rendering SLS 'base:telegraf.agent' failed: Jinja variable 'str object' has no attribute 'get'

### ISSUE THREAD

**Issue by brenwhyte** [salt-formulas/salt-formula-telegraf#2]
Getting the below render error from Salt.

```
    Data failed to compile:
----------
    Rendering SLS 'base:telegraf.agent' failed: Jinja variable 'str object' has no attribute 'get'
/var/cache/salt/minion/files/base/telegraf/map.jinja(23):
---
[...]
}, merge=salt['pillar.get']('telegraf:remote_agent')) %}

{# Collect configuration from */meta/telegraf.yml #}
{%- set telegraf_grains = {'telegraf': {'agent': {'input': {}}, 'remote_agent': {'input':{}, 'output':{}}}} %}
{%- for service_name, service in pillar.items() %}
  {%- if service.get('_support', {}).get('telegraf', {}).get('enabled', False) %}    <======================
    {%- set grains_fragment_file = service_name+'/meta/telegraf.yml' %}
    {%- macro load_grains_file() %}{% include grains_fragment_file ignore missing %}{% endmacro %}
    {%- set grains_yaml = load_grains_file()|load_yaml %}
    {%- if grains_yaml is mapping %}
      {%- set telegraf_grains = salt['grains.filter_by']({'default': telegraf_grains}, merge={'telegraf': grains_yaml}) %}
[...]
---
```

Basic pillar file:
```
telegraf:
  agent:
    enabled: true
    output:
      influxdb:
        urls:
          - http://127.0.0.1:9096
        database: telegraf
    input:
      cpu:
        totalcpu: totalcpu_value
```

Any thoughts?
